version: '3.8'

services:
  postgres:
    image: postgres:16.1
    restart: always
    env_file:
      - .env
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
