openapi: 3.0.0

info:
  title: SMA Travel Fare Calculator
  version: 1.0.0
  description: Calculate travel fares

servers:
  - url: http://localhost/api/v1

paths:
  /travel/calculate/upload:
    post:
      tags: ['Travel']
      summary: Uploads a CSV file.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalFare:
                    type: number
                    example: 100.00
        '400':
          description: Bad request.
        '403':
          description: Forbidden.
        '500':
          description: Server error.
