export const PEAK_HOUR_WEEKDAY_MORNING_START = 8
export const PEAK_HOUR_WEEKDAY_MORNING_END = 10
export const PEAK_HOUR_WEEKDAY_EVENING_START = 16
export const PEAK_HOUR_WEEKDAY_EVENING_END = 19
export const PEAK_HOUR_WEEKEND_MORNING_START = 10
export const PEAK_HOUR_WEEKEND_MORNING_END = 14
export const PEAK_HOUR_WEEKEND_EVENING_START = 18
export const PEAK_HOUR_WEEKEND_EVENING_END = 23
